name: Publish To Nuget

on:
  workflow_dispatch 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Run
      run: 
         cd ${{ github.workspace }}\src 
         ${{ github.workspace }}\src\nuget.bat
         cd ${{ github.workspace }}\src\packages
         ${{ github.workspace }}\src\publishnuget.bat ${{ secrets.NUGET_API_KEY }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Nethereum
        path: |
              ${{ github.workspace }}/src/packages/*.*
  
